---
apiVersion: v1
kind: Service
metadata:
  name: postgres-file-service
  labels:
    creator: chaitanya
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: postgres-file

...