---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-file-deployment
  labels:
    type: redis-file
    creator: chaitanya
spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis-file
  template:
    metadata:
      name: my-redis-file-pod
      labels:
        type: redis-file
    spec:
      containers:
        - name: my-redis-file
          image: redis
...

