---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    creator: chaitanya
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    type: result-app

...